language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python -m pytest --cov tests/
after_success: coveralls
