language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - coverage run -m --source=. --branch pytest tests
after_success: coveralls
