version: 1

formatters:
  console_formatter:
    format: '%(asctime)s - %(filename)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M'
  file_formatter:
    format: '%(asctime)s - %(filename)s - %(funcName)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M'

filters:
  info_filter:
    (): web_crawler.filter.LogLevelFilter
    level: 20
  error_filter:
    (): web_crawler.filter.LogLevelFilter
    level: 40

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: file_formatter
    level: DEBUG
    filename: web_crawler.log
    mode: 'w'
    maxBytes: 10485760
    backupCount: 5
  stdout_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: console_formatter
    stream: ext://sys.stdout
    filters: [info_filter]
  stderr_handler:
    class: logging.StreamHandler
    level: WARN
    formatter: console_formatter
    stream: ext://sys.stderr
    filters: [error_filter]

loggers:
  web_crawler_logger:
    level: DEBUG
    handlers: [file, stdout_handler, stderr_handler]
    propagate: no
